name: 🔌 Plugin | Package and release

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    tags:
      - '*'
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - oqtopus/**
  workflow_dispatch:


jobs:
  plugin-package:
    name: Packages and releases plugin
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Qt lrelease
        run: |
          sudo apt-get update
          sudo apt-get install qtbase5-dev qttools5-dev-tools

      - name: Install qgis-plugin-ci
        run: pip install qgis-plugin-ci>=2.8.6

      - name: Package PyPI Packages
        run: |
          for LIB in pgserviceparser pum; do
            DNL=$(git grep $LIB requirements.txt | cut -d: -f2)
            pip download $DNL --no-deps --only-binary :all: -d temp/
          done
          unzip -o "temp/*.whl" -d oqtopus/libs
          rm -r temp
          # set write rights to group (because qgis-plugin-ci needs it)
          chmod -R g+w oqtopus/libs


      - name: Package
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        run: |
          VERSION=0.0.0
          qgis-plugin-ci -v package ${VERSION} \
            --allow-uncommitted-changes \
            --asset-path oqtopus/libs \

      - uses: actions/upload-artifact@v4
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        with:
          name: oqtopus_dev
          path: oqtopus.0.0.0.zip
          if-no-files-found: error

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          VERSION=${{ github.ref_name }}
          qgis-plugin-ci release ${VERSION} \
            --allow-uncommitted-changes \
            --asset-path oqtopus/libs \
            --github-token ${{ secrets.GITHUB_TOKEN }} \
            --osgeo-username ${{ secrets.OSGEO_PLUGIN_USERNAME }} \
            --osgeo-password ${{ secrets.OSGEO_PLUGIN_PASSWORD }}
